import type { IconType } from 'react-icons';
import {
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiTailwindcss,
  SiHtml5,
  SiCss,
  SiNodedotjs,
  SiNestjs,
  SiExpress,
  SiGraphql,
  SiPython,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiPrisma,
  SiVercel,
  SiDocker,
  SiGithubactions,
  SiNginx,
  SiGit,
  SiJest,
  SiVitest,
  SiFigma,
  SiLinux,
  SiSocketdotio,
  SiStripe,
  SiTestinglibrary,
  SiOpenai,
  SiLangchain,
  SiHuggingface,
} from 'react-icons/si';

export interface SkillIconDef {
  icon: IconType;
  color: string;
}

export const skillIconMap: Record<string, SkillIconDef> = {
  TypeScript:       { icon: SiTypescript,        color: '#3178C6' },
  React:            { icon: SiReact,              color: '#61DAFB' },
  'Next.js':        { icon: SiNextdotjs,          color: 'currentColor' },
  'Vue.js':         { icon: SiVuedotjs,           color: '#4FC08D' },
  'Tailwind CSS':   { icon: SiTailwindcss,        color: '#06B6D4' },
  'HTML / CSS':     { icon: SiHtml5,              color: '#E34F26' },
  HTML5:            { icon: SiHtml5,              color: '#E34F26' },
  CSS3:             { icon: SiCss,                color: '#1572B6' },
  'Node.js':        { icon: SiNodedotjs,          color: '#339933' },
  NestJS:           { icon: SiNestjs,             color: '#E0234E' },
  Express:          { icon: SiExpress,            color: 'currentColor' },
  GraphQL:          { icon: SiGraphql,            color: '#E10098' },
  Python:           { icon: SiPython,             color: '#3776AB' },
  PostgreSQL:       { icon: SiPostgresql,         color: '#4169E1' },
  MySQL:            { icon: SiMysql,              color: '#4479A1' },
  MongoDB:          { icon: SiMongodb,            color: '#47A248' },
  Redis:            { icon: SiRedis,              color: '#FF4438' },
  Prisma:           { icon: SiPrisma,             color: 'currentColor' },
  Vercel:           { icon: SiVercel,             color: 'currentColor' },
  Docker:           { icon: SiDocker,             color: '#2496ED' },
  'GitHub Actions': { icon: SiGithubactions,      color: '#2088FF' },
  Nginx:            { icon: SiNginx,              color: '#009639' },
  Git:              { icon: SiGit,                color: '#F05032' },
  Jest:             { icon: SiJest,               color: '#C21325' },
  Vitest:           { icon: SiVitest,             color: '#6E9F18' },
  'Jest / Vitest':  { icon: SiVitest,             color: '#6E9F18' },
  Playwright:       { icon: SiTestinglibrary,      color: '#E33332' },
  Figma:            { icon: SiFigma,              color: '#F24E1E' },
  Linux:            { icon: SiLinux,              color: 'currentColor' },
  'Socket.io':        { icon: SiSocketdotio,    color: 'currentColor' },
  Stripe:             { icon: SiStripe,          color: '#635BFF' },
  'OpenAI API':       { icon: SiOpenai,          color: 'currentColor' },
  LangChain:          { icon: SiLangchain,       color: '#1C3C3C' },
  'Hugging Face':     { icon: SiHuggingface,     color: '#FFD21E' },
};
